Add Tools directory and files to Feat/dwin nextgen support
CR6Community/CR-6-touchscreen pull request #68
Opened 2022-02-04 04:17 UTC by Thinkersbluff

I have forked this repository, to help me learn how to work with these tools on a local copy of my own, and as requested in the extui ReadMe.

I notice that the extui ReadMe contains a fairly detailed "How To" section, describing the toolset and workflow to be used by Community members proposing changes to the UI.  The link to the DGUS v8.0 tool is broken, now.  I had already followed it to download v8.0.1.1 some time ago, so I have a local copy I can upload.

I recommend that we deliberately mitigate the risk that online access to DGUSv8.2.14 and any other tools we decide to use may also be moved or terminated.  

Specifically, I recommend that we add a Tools directory to this Feat/dwin nextgen support branch, and that we upload into it a master copy of each open-source toolset we decide to use.

2022-04-26 18:42 UTC, Sebazzz commented
LGTM so far!

Let's refine the README and flashing instructions a bit, remove the DRAFT files (so the repository size is less inflated - let's squash-commit-merge this so those files won't exist in the end result), and then I think we can offer these files as part of a 6.1b beta release.

2022-04-26 19:58 UTC, Thinkersbluff commented
So this is part of what I mean when I say I am not very GitHub literate.  

I did not realize that continuing to commit changes to the same branch on my fork would result in a continuing evolution of the PR.

I have removed the DRAFT folders.

I am now refining the README.MD file in the RC folder.
Are there specific points you would like me to add/delete/modify?

2022-04-27 16:00 UTC, Sebazzz commented
The most important thing to clarify is the DWIN OS upgrade. 

As for the rest, check my remarks in the "files" tab.

2022-04-27 16:01 UTC, Sebazzz requested changes

2022-04-27 16:01 UTC, Sebazzz commented on README.md
> +Attempt to extend the CR-6 touch screen software to operate with newer display hardware being sold with CR6 machines as of approximately Dec 2021.
We might want to clarify here that the firmware is also still valid for "old models".

2022-04-27 16:01 UTC, Sebazzz commented on README.md
> +This repository belongs to Thinkersbluff and is forked from [the CR6Community Touchscreen Firmware repository](https://github.com/CR6Community/CR-6-touchscreen).
Let's remove this before merging back 🤓

2022-04-27 16:01 UTC, Sebazzz commented on README.md
> +This project is not yet ready to release a stable version of the updated display firmware.
I propose we merge this back to master as this is the only way forward, given the binary nature of the project,.

2022-04-27 16:01 UTC, Sebazzz commented on doc/build/DRAFT_21 Apr 2022/CR-6 kernel upgrade/README.txt
> + - Legacy display hardware (Dec 2021 or earlier) does not run on v4.5 or v4.7
We need to refine this to make sure and also include instructions on how to find the current version of the display firmware (the empty DWIN_SET folder I believe)

2022-04-27 16:01 UTC, Sebazzz commented on doc/build/DRAFT_21 Apr 2022/CR-6 kernel upgrade/README.txt
> + - Legacy display hardware (Dec 2021 or earlier) does not run on v4.5 or v4.7
And of course incorporate this back into the main README.

2022-04-27 16:57 UTC, Thinkersbluff commented on README.md
> +This project is not yet ready to release a stable version of the updated display firmware.
There is a lot of detailed info in the current extui baseline README about how to contribute changes to this firmware.
I found it very helpful when I was working with it, but I deleted it completely from the README in the feat branch.
If we merge this branch back as-is, will all of that good info disappear?  I was hoping to keep it but update it to point to the new tools & to add any new instructions that may be required, but we could also create a separate document "For Developers Only" and plan to refine that in a follow-on PR.

2022-04-27 19:03 UTC, Thinkersbluff commented
I believe this conflicting part of the PR has been overtaken by events.
As long as the latest TFT files are kept in the merge, we will be ok ignoring these ones.

2022-04-28 17:40 UTC, Sebazzz commented
I see what the problem with merging is. This PR wants to merge to the feature branch instead of extui, but we should merge to extui instead.

2022-04-28 17:41 UTC, Sebazzz commented
Changed to extui.

2022-04-28 17:42 UTC, Sebazzz approved these changes

2022-04-28 17:43 UTC, merged